name: Publish to Cloudflare Pages
run-name: ${{ github.actor }} is publishing to Cloudflare Pages 🚀
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          npm ci
      - name: Set version number
        run: |
          set -x
          RAW_TAG="${{ github.event.release.tag_name }}"
          CLEAN_TAG="${RAW_TAG#v}"
          echo "Set version to $CLEAN_TAG"
          npm version $CLEAN_TAG --git-tag-version=false

      - name: Build app
        run: |
          npm run build
      - name: Upload to Cloudflare
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=litra --branch=main
